USE [master]
GO

/****** Object:  Database [AppsureTest]    Script Date: 2016-08-16 07:04:54 PM ******/
CREATE DATABASE [AppsureTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppsureTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\AppsureTest.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AppsureTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\AppsureTest_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AppsureTest] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppsureTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AppsureTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AppsureTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AppsureTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AppsureTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AppsureTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [AppsureTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AppsureTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AppsureTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AppsureTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AppsureTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AppsureTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AppsureTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AppsureTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AppsureTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AppsureTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AppsureTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AppsureTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AppsureTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AppsureTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AppsureTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AppsureTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AppsureTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AppsureTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AppsureTest] SET  MULTI_USER 
GO

ALTER DATABASE [AppsureTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AppsureTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AppsureTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AppsureTest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AppsureTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AppsureTest] SET  READ_WRITE 
GO


